### ISSUE TITLE
Products on the site

### ISSUE THREAD

**Issue by Jamsson** [Nasus20202/AspShop#21]
Thanks for your help, another question is, what to do to make the site appeared products and their descriptions and all that is associated with it, just as I realized in the repository is not all folders and files.

**Comment by Jamsson** [comment]
I forgot to ask how to get into the admin panel, if it depends a lot on the database I use local PostgreSql

**Comment by Nasus20202** [comment]
To use the admin panel, you have to register a new user, then connect to your DB and change your role to "admin". You can run this SQL query - `UPDATE Users SET Role = "admin" WHERE Email = "<your@email.com>";`.
After that log in again and you should be able to use the admin panel (check `/admin` path). Here you can add new users, products, categories etc.

**Comment by Jamsson** [comment]
Hello, I can't understand if I connected PostgreSql correctly:
```
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Npgsql.EntityFrameworkCore.PostgreSQL;

namespace ShopWebApp
{
    public class ShopDatabase : DbContext
    {
        public DbSet<Category> Categories { get; set; }
        public DbSet<Subcategory> Subcategories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<ProductOrder> ProductOrders { get; set; }

        public string DbConnectionString { get; set; }

        public ShopDatabase()
        {
            DbConnectionString = "Host=localhost;Database=ShopDataBase;Username=AdminShop;Password=12345678";
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(DbConnectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProductOrder>()
                .HasKey(po => new { po.OrderId, po.ProductId });
            modelBuilder.Entity<ProductOrder>()
                .HasOne(o => o.Order)
                .WithMany(po => po.ProductOrders)
                .HasForeignKey(po => po.OrderId);
            modelBuilder.Entity<ProductOrder>()
                .HasOne(po => po.Product)
                .WithMany(p => p.ProductOrders)
                .HasForeignKey(po => po.ProductId);
        }
    }
}
```
 the account is created and everything works, but when I execute the command, an error appears:
```
 [2024-11-12 15:50:38] Connected
ShopDataBase.public> UPDATE Users SET Role = "admin" WHERE Email = "test@test.test"
[2024-11-12 15:50:38] [42P01] ERROR: relation "users" does not exist
[2024-11-12 15:50:38] Позиция: 8
ShopDataBase.public> UPDATE Users SET Role = "admin" WHERE Email = "test@test.test"
[2024-11-12 15:50:47] [42P01] ERROR: relation "users" does not exist
[2024-11-12 15:50:47] Позиция: 8
```
thank you for helping and not ignoring

**Comment by Jamsson** [comment]
I gave my account the admin role, but when I click on the "Panel" button on the bottom right, the screen displays the message "Niestety, nie masz dostępu do tej strony". What do I need to do to get access? Thank you for answering and not ignoring me.

**Comment by Nasus20202** [comment]
Try logging out and then authorizing again - the role is attached to the session cookie. However, if you see the "Panel" button, your permissions already should be high enough. You can also try any of these roles "admin, manager, editor, employee".

**Comment by Jamsson** [comment]
# An unhandled exception occurred while processing the request.

**ArgumentNullException: Value cannot be null. (Parameter 'key')**  
`System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)`

---

### Stack | Query | Cookies | Headers | Routing

---

**ArgumentNullException: Value cannot be null. (Parameter 'key')**  
`System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)`  
`System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey key, TValue value)`  
`ShopWebApp.HomeController.Index()` in **HomeController.cs**
```csharp
    Categories.Add(category.Name, category.Code);
```
`lambda_method13(Closure , object , object[] )`
`Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()`
`Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)`
`Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()`
`Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)`
`Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)`
`Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)`
`Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)`
`Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)`
`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)`

**Comment by Jamsson** [comment]
```csharp
public IActionResult Index()
        {
            var model = new BaseViewModel("Sklep");
            using (var db = new ShopDatabase())
            {
                if (User.Identity.IsAuthenticated)
                {
                    var user = (from c in db.Users
                                where c.Email == User.Identity.Name
                                select c).FirstOrDefault();
                    model.User.Name = user.Name;
                    model.User.Surname = user.Surname;
                    model.User.Email = user.Email;
                }
                if (db.Products.Where(p => p.Enabled && p.Stock != 0).Count() > 0)
                {
                    int maxId = db.Products.Max(p => p.ProductId), id;
                    Random random = new Random();
                    do
                    {
                        id = random.Next(maxId + 1);
                    }
                    while (db.Products.Where(p => p.ProductId == id && p.Enabled && p.Stock != 0).Count() == 0);
                    ViewBag.product = db.Products.Where(p => p.ProductId == id).FirstOrDefault();
                    ViewBag.productExists = true;
                }
                else
                {
                    ViewBag.productExists = false;
                }
                Dictionary<string, string> Categories = new Dictionary<string, string>();
                foreach(Category category in db.Categories.Where(c => c.Enabled))
                {
                    Categories.Add(category.Name, category.Code);
                }
                ViewBag.categoriesExist = Categories.Count > 0 ? true : false;
                ViewBag.categories = Categories;
            }

            return View(model);
        }

**Comment by Jamsson** [comment]
I fixed the error, I accidentally left the category names blank
Thank you so much for the website model, thanks to you I will be able to pass the study practice
